<?php
$form->setAttribute('action', $this->url('acl/default',array('controller'=>'roles','action'=>'edit')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="box_top">
    <h2 class="icon frames">Editar perfis de usuários</h2>

    <ul class="sorting">
        <li><a href="<?php echo $this->url('acl/default', array('controller' => 'roles', 'action' => 'index'));  ?>" class="active">Listar</a></li>
    </ul>
</div>

<div class="box_content padding">

    <div class="field">
        <label class="left">Nome: </label>
        <?php echo $this->formRow($form->get('nome')); ?>
    </div>

    <div class="field">
        <label class="left">Herda: </label>
        <?php echo $this->formRow($form->get('parent')); ?>
    </div>

    <div class="field">
        <label class="left">Admin?: </label>
        <?php echo $this->formRow($form->get('isAdmin')); ?>
    </div>

    <label class="left"></label>
    <?php echo $this->formRow($form->get('id'));  ?>
    <button><?php echo $this->formRow($form->get('submit'));  ?>Salvar</button>

</div>
<?php
echo $this->form()->closeTag($form);