<?php

namespace DoctrineORMModule\Proxy\__CG__\Adm\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Militar extends \Adm\Entity\Militar implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getMilcodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["milcodigo"];
        }
        $this->__load();
        return parent::getMilcodigo();
    }

    public function setMilcpf($milcpf)
    {
        $this->__load();
        return parent::setMilcpf($milcpf);
    }

    public function getMilcpf()
    {
        $this->__load();
        return parent::getMilcpf();
    }

    public function setMilidt($milidt)
    {
        $this->__load();
        return parent::setMilidt($milidt);
    }

    public function getMilidt()
    {
        $this->__load();
        return parent::getMilidt();
    }

    public function setMilmatricula($milmatricula)
    {
        $this->__load();
        return parent::setMilmatricula($milmatricula);
    }

    public function getMilmatricula()
    {
        $this->__load();
        return parent::getMilmatricula();
    }

    public function setMilnome($milnome)
    {
        $this->__load();
        return parent::setMilnome($milnome);
    }

    public function getMilnome()
    {
        $this->__load();
        return parent::getMilnome();
    }

    public function setMilnomeguerra($milnomeguerra)
    {
        $this->__load();
        return parent::setMilnomeguerra($milnomeguerra);
    }

    public function getMilnomeguerra()
    {
        $this->__load();
        return parent::getMilnomeguerra();
    }

    public function setMildtnascimento($mildtnascimento)
    {
        $this->__load();
        return parent::setMildtnascimento($mildtnascimento);
    }

    public function getMildtnascimento()
    {
        $this->__load();
        return parent::getMildtnascimento();
    }

    public function setMilpassword($milpassword)
    {
        $this->__load();
        return parent::setMilpassword($milpassword);
    }

    public function getMilpassword()
    {
        $this->__load();
        return parent::getMilpassword();
    }

    public function setMiltelefone($miltelefone)
    {
        $this->__load();
        return parent::setMiltelefone($miltelefone);
    }

    public function getMiltelefone()
    {
        $this->__load();
        return parent::getMiltelefone();
    }

    public function setMilendereco($milendereco)
    {
        $this->__load();
        return parent::setMilendereco($milendereco);
    }

    public function getMilendereco()
    {
        $this->__load();
        return parent::getMilendereco();
    }

    public function setMilemail($milemail)
    {
        $this->__load();
        return parent::setMilemail($milemail);
    }

    public function getMilemail()
    {
        $this->__load();
        return parent::getMilemail();
    }

    public function setPgrcodigo($pgrcodigo)
    {
        $this->__load();
        return parent::setPgrcodigo($pgrcodigo);
    }

    public function getPgrcodigo()
    {
        $this->__load();
        return parent::getPgrcodigo();
    }

    public function setRoleid($roleid)
    {
        $this->__load();
        return parent::setRoleid($roleid);
    }

    public function getRoleid()
    {
        $this->__load();
        return parent::getRoleid();
    }

    public function getMiltelefonesec()
    {
        $this->__load();
        return parent::getMiltelefonesec();
    }

    public function getMilemailsec()
    {
        $this->__load();
        return parent::getMilemailsec();
    }

    public function getQuacodigo()
    {
        $this->__load();
        return parent::getQuacodigo();
    }

    public function setMiltelefonesec($miltelefonesec)
    {
        $this->__load();
        return parent::setMiltelefonesec($miltelefonesec);
    }

    public function setMilemailsec($milemailsec)
    {
        $this->__load();
        return parent::setMilemailsec($milemailsec);
    }

    public function setQuacodigo($quacodigo)
    {
        $this->__load();
        return parent::setQuacodigo($quacodigo);
    }

    public function encryptPassword($password)
    {
        $this->__load();
        return parent::encryptPassword($password);
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'milcodigo', 'milcpf', 'milidt', 'milmatricula', 'milnome', 'milnomeguerra', 'mildtnascimento', 'milpassword', 'miltelefone', 'miltelefonesec', 'milendereco', 'milemail', 'milemailsec', 'pgrcodigo', 'roleid', 'quacodigo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}