<?php

namespace DoctrineORMModule\Proxy\__CG__\Adm\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PostoGraduacao extends \Adm\Entity\PostoGraduacao implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getPgrcodigo()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["pgrcodigo"];
        }
        $this->__load();
        return parent::getPgrcodigo();
    }

    public function setPgrdescricao($pgrdescricao)
    {
        $this->__load();
        return parent::setPgrdescricao($pgrdescricao);
    }

    public function getPgrdescricao()
    {
        $this->__load();
        return parent::getPgrdescricao();
    }

    public function setPgrsigla($pgrsigla)
    {
        $this->__load();
        return parent::setPgrsigla($pgrsigla);
    }

    public function getPgrsigla()
    {
        $this->__load();
        return parent::getPgrsigla();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'pgrcodigo', 'pgrdescricao', 'pgrsigla');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}