<div class="grid_24">
    <div class="box_top">
        <h2 class="icon pages">Consultar Militar</h2>
        <ul class="sorting">
            <li><a href="<?php echo $this->url('adm/default', array('controller' => 'militar', 'action' => 'cadastrar')); ?>" class="active">Cadastrar Novo</a></li>
        </ul>
    </div>

    <div class="box_content">
        <table class="sorting">
            <thead>
                <tr>
                    <th class="align_left">Nome Guerra</th>
                    <th class="align_left center">IDT</th>
                    <th class="align_left center">Matricula</th>
                    <th class="align_left center">Email</th>
                    <th class="align_left center">Telefone</th>
                    <th class="align_left center tools">Operações</th>
                </tr>
            </thead>
            <tbody>
                <?php if ($this->result) : ?>
                    <?php foreach ($this->result as $i => $row) : ?>
                    <tr>
                        <td class="align_left"><?php echo $row->getMilnomeguerra(); ?></td>
                        <td class="align_left center"><?php echo $row->getMilidt(); ?></td>
                        <td class="align_left center"><?php echo $row->getMilmatricula(); ?></td>
                        <td class="align_left center"><?php echo $row->getMilemail(); ?></td>
                        <td class="align_left center"><?php echo $row->getMiltelefone(); ?></td>
                        <td class="align_left tools center">
                            <a href="<?php echo $this->url('adm/default', array('controller' => 'militar', 'action' => 'atualizar', 'id' => $row->getMilcodigo())); ?>" class="edit tip" title="edit">edit</a>
                            <a href="<?php echo $this->url('adm/default', array('controller' => 'militar', 'action' => 'excluir', 'id' => $row->getMilcodigo())); ?>" class="delete tip" title="delete">delete</a>
                            <!--<a href="#" class="view tip" title="view">view</a>-->
                        </td>
                    </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>