<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlaRepository extends EntityRepository
{
}