<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaRepository extends EntityRepository
{
}