<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MilitarAlaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilitarAlaRepository extends EntityRepository
{
}