<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MilitarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MilitarRepository extends EntityRepository
{

    public function findByMatriculaAndPassword($matricula, $password)
    {
        $user = $this->findOneBy(array('milmatricula' => $matricula));

        if ($user) {
            $hashSenha = $user->encryptPassword($password);
            if ($hashSenha == $user->getMilpassword()) {
                return $user;
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

}