<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostoGraduacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostoGraduacaoRepository extends EntityRepository
{
}