<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuadroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuadroRepository extends EntityRepository
{
}