<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicoRepository extends EntityRepository
{
//    public function buscaEscala12hPorMes($mes)
//    {
//        \Zend\Debug\Debug::dump(date("Y-{$mes}"));
//        exit();
//
//        $queryBuilder = $this->getEntityManager()->createQueryBuilder();
//        $query = $queryBuilder->select('S')
//                ->from('Adm\Entity\Servico', 'S')
//                ->where("(SERDATA > '2014-05' AND SERDATA < '2014-07')");
//        \Zend\Debug\Debug::dump($query->getDQL());
//        exit();
//
//        return $query->getDQL();
//    }
}