<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TipoSituacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoSituacaoRepository extends EntityRepository
{
}