<?php

namespace Adm\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrocaServicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrocaServicoRepository extends EntityRepository
{
}