<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl  = function ($page) use ($urlPattern) {
if (!preg_match('/page/', $urlPattern))
    return $urlPattern . '/page/' . (int) $page;
else
    return preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern);
};
if ($this->pageCount):?>
<div class="row">
  <div class="col-lg-7">
      <div class="dataTables_paginate paging_bootstrap pagination">
          <ul>
              <?php if (isset($this->previous)): ?>
                  <li class="prev"><a href="<?php echo $formatUrl($this->previous); ?>">«</a></li>
              <?php else: ?>
                  <li class="prev disabled"><a href="#">«</a></li>
              <?php endif; ?>

                    <?php foreach ($this->pagesInRange as $page): ?>
                        <?php if ($page != $this->current): ?>
                        <li>
                            <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
                        </li>
                        <?php else: ?>
                        <li class="active">
                            <a href="#"><?php echo $page; ?></a>
                        </li>
                        <?php endif; ?>
                    <?php endforeach; ?>

              <?php if (isset($this->next)): ?>
                  <li class="prev"><a href="<?php echo $formatUrl($this->next); ?>">»</a></li>
              <?php else: ?>
                  <li class="prev next disabled"><a href="#">»</a></li>
              <?php endif; ?>
          </ul>
      </div>
  </div>
</div>
<?php endif; ?>
