<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <base href="<?php echo $this->serverUrl() . $this->basePath(); ?>/" />
        <?php echo $this->headTitle('Siscala - Sistema de Controle de Escala')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Imports General CSS and jQuery CSS -->
        <link href="<?= $this->basePath() ?>/assets/vendor/css/screen.css" rel="stylesheet" media="screen" type="text/css" />

        <!-- CSS for Fluid and Fixed Widths - Double to prevent flickering on change -->
        <link href="<?= $this->basePath() ?>/assets/vendor/css/fixed.css" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->basePath() ?>/assets/vendor/css/fixed.css" rel="stylesheet" media="screen" type="text/css" class="width" />

        <!-- IE Stylesheet ie7 - Added in 1.2 -->
        <!--[if lt IE 8]> <html lang="en" class="ie7"> <![endif]-->

        <!-- IE Stylesheet ie8 - Added in 1.1 -->
        <!--[if IE 8 ]> <html lang="en" class="ie8"> <![endif]-->

        <!-- CSS for Theme Styles - Double to prevent flickering on change -->
        <link href="<?= $this->basePath() ?>/assets/vendor/css/theme/blue.css" rel="stylesheet" media="screen" type="text/css" />
        <link href="<?= $this->basePath() ?>/assets/vendor/css/theme/blue.css" rel="stylesheet" media="screen" type="text/css" class="theme" />

        <!-- IE Canvas Fix for Visualize Charts - Added in 1.1 -->
        <!--[if IE]><script type="text/javascript" src="js/excanvas.js"></script><![endif]-->

        <!-- jQuery thats loaded before document ready to prevent flickering - Rest are found at the bottom -->
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
        <!--<script type="text/javascript" src="<?#= $this->basePath() ?>/assets/vendor/js/jquery-1.4.1.min.js"></script>-->
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.cookie.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.styleswitcher.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.visualize.js"></script>
    </head>

    <body>
        <!-- Start: Page Wrap -->
        <div id="wrap" class="container_24">

            <!-- Header Grid Container: Start -->
            <div class="grid_24">

                <!-- User Panel: Start -->
                <div id="userpanel">

                    <!-- User: Start -->
                    <ul id="user" class="dropdown">
                        <li class="topnav">
                            <!-- User Name -->
                            <a href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>" class="top icon user">Admin</a>

                            <!-- User Dropdown Content: Start -->
                            <ul class="subnav">
                                <li><a href="<?=$this->url('acl/default', array('controller' => 'roles', 'action' => 'index'));?>" class="icon settings">Perfil</a></li>
                                <li><a href="<?=$this->url('acl/default', array('controller' => 'resources', 'action' => 'index'));?>" class="icon settings">Página de Acesso</a></li>
                                <li><a href="<?=$this->url('acl/default', array('controller' => 'privileges', 'action' => 'index'));?>" class="icon settings">Privilégio</a></li>
                                <!--<li><a href="#messages" class="icon chatbubbles popup">Mensagens</a></li>-->
                                <li><a href="<?=$this->url('autenticacao/default', array('controller' => 'index', 'action' => 'logout'));?>" class="icon lock">Sair</a></li>
                            </ul>
                            <!-- User Dropdown Content: End -->
                        </li>
                    </ul>
                    <!-- User: End -->

                    <!-- Messages: Start -->
<!--                                        <ul class="messages">
                                             Messages amount with Popup and Tip
                                            <li><a href="#messages" class="newmsg tip popup" title="16 Mensagens"> <span>16</span></a></li>
                                        </ul>-->
                    <!-- Messages: End -->

                    <!-- Messages Popup Content: Start -->
<!--                                        <div class="box_content padding hide" id="messages">
                                            <form>

                                                 Message From User: Start
                                                <h6>
                                                    <span class="icon user"></span> <a href="#">Jenny</a> <span class="nobold">says</span>
                                                    <small class="right grey nobold">2 hours ago</small>
                                                </h6>
                                                <p>
                                                    Lorem ipsum dolor sit amet, consectetur adipisicing elit,
                                                    sed do eiusmod tempor incididunt ut labore et dolore magna
                                                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                                                </p>
                                                 Message From User: End

                                                 Message From User: Start
                                                <h6>
                                                    <span class="icon user"></span> <a href="#">Jenny</a> <span class="nobold">says</span>
                                                    <small class="right grey nobold">15 hours ago</small>
                                                </h6>
                                                <p>
                                                    Sed do eiusmod tempor incididunt ut labore et dolore magna
                                                    aliqua. Ut enim ad minim veniam, quis nostrud exercitation.
                                                </p>
                                                 Message From User: End

                                                 Quick Reply: Start
                                                <div class="field">
                                                    <label>
                                                        <span class="icon chatbubbles"></span>
                                                        Quick Reply
                                                    </label>
                                                    <textarea cols="50" rows="7"></textarea>
                                                </div>

                                                <button>Send</button>
                                                <button class="secondary" type="reset">Reset</button>
                                                <button disabled="">Disabled Button</button>
                                                 Quick Reply: End

                                            </form>
                                        </div>-->
                    <!-- Messages Popup Content: End -->

                    <!-- Style (Themes) Switcher: Start -->
                    <ul id="style" class="dropdown right">
                        <li class="topnav">
                            <a href="#" class="top icon brush">Estilo</a>

                            <!--Style (Themes) Switcher Content: Start-->
                            <ul class="subnav">
                                <li><a href="#blue" class="icon circle">Azul</a></li>
                                <li><a href="#light" class="icon circle">Claro</a></li>   <!--Added in 1.2-->
                                <li><a href="#red" class="icon circle">Vermelho</a></li>
                                <li><a href="#dark" class="icon circle">Escuro</a></li>
                                <li><a href="#green" class="icon circle">Verde</a></li>
                                <li><a href="#purple" class="icon circle">Roxo</a></li>
                                <li><a href="#brown" class="icon circle">Marron</a></li>
                            </ul>
                            <!--Style (Themes) Switcher Content: End-->
                        </li>
                    </ul>
                    <!-- Style Switcher: End -->

                    <!-- Width Switcher: Start -->
                    <ul id="width" class="dropdown right">
                        <li class="topnav">
                            <a href="#" class="top icon coverflow">Tamanho</a>

                            <!-- Width Switcher Content: Start -->
                            <ul class="subnav">
                                <li><a href="#fluid" class="icon coverflow">Grande</a></li>
                                <li><a href="#fixed" class="icon coverflow">Pequeno</a></li>
                            </ul>
                            <!-- Width Switcher Content: End -->
                        </li>
                    </ul>
                    <!-- Width Switcher: End -->

                </div>
                <!-- User Panel: End -->

                <!-- Header: Start -->
                <div id="header">

                    <!-- Logo: Start -->
                    <a href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>" id="logo">Siscala - Painel de Controle</a>
                    <!-- Logo: End -->

                    <!-- Navigation: Start -->
                    <ul id="navigation" class="dropdown">
                        <li><a class="dashboard active" href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>">Home</a></li>

                        <!-- Navigation Dropdown Menu Item: Start -->
                        <li class="topnav">
                            <a class="frames" href="#">Cadastrar</a>

                            <!-- Navigation Dropdown Menu Item Content: Start -->
                            <ul class="subnav">
                                <li><a href="<?=$this->url('adm/default', array('controller' => 'militar', 'action' => 'index'));?>" class="icon blocks">Militar</a></li>
                                <li><a href="<?=$this->url('adm/default', array('controller' => 'ala'    , 'action' => 'index'));?>" class="icon blocks">Militar/Ala</a></li>
                                <li><a href="<?=$this->url('adm/default', array('controller' => 'militar', 'action' => 'situacao'));?>" class="icon blocks">Militar/Situação</a></li>
                            </ul>
                            <!-- Navigation Dropdown Menu Item Content: End -->
                        </li>
                        <!-- Navigation Dropdown Menu Item: End -->

                        <!-- Navigation Dropdown Menu Item: Start -->
                        <li class="topnav">
                            <a class="pages" href="#">Realizar</a>

                            <!-- Navigation Dropdown Menu Item Content: Start -->
                            <ul class="subnav">
<!--                                <li><a href="<? #=$this->url('adm/default', array('controller' => 'pedido', 'action' => 'cadastrar'));?>" class="icon laptop">Pedido</a></li>
                                <li><a href="<? #=$this->url('adm/default', array('controller' => 'entrega', 'action' => 'cadastrar'));?>" class="icon archive">Entrega</a></li>-->
                                <!-- Sub Navigation: Start -->
<!--                                <li>
                                    <a href="#" class="icon point_right">Sub Nav</a>

                                    <ul>
                                        <li><a href="#" class="download list">Example</a></li>
                                        <li><a href="#" class="upload list">Example</a></li>
                                        <li><a href="#" class="search list">Example</a></li>
                                    </ul>

                                </li>-->
                                <!-- Sub Navigation: End -->

                            </ul>
                            <!-- Navigation Dropdown Menu Item Content: End -->

                        </li>
                        <!-- Navigation Dropdown Menu Item: End -->

                        <!-- Navigation Menu Item: Start -->
                        <!--<li><a class="pictures" href="gallery.html">NF</a></li>-->
                        <!-- Navigation Menu Item: End -->

                    </ul>
                    <!-- Navigation: End -->

                </div>
                <!-- Header: End -->

                <!-- Breadcrumb Bar: Start -->
                <div id="breadcrumb">

                    <!-- Breadcrumb: Start -->
                    <ul class="left">
                        <li class="icon dashboard"><a href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>">Página Inicial</a></li>
                    </ul>
                    <!-- Breadcrumb: End -->

                    <!-- Breadcrumb Icon Links: Start -->
                    <ul class="right">

                        <li><a href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>" class="icon home tip" title="Página Inicial">Página Inicial</a></li>
                    </ul>
                    <!-- Breadcrumb Icon Links: End -->

                </div>
                <!-- Breadcrumb Bar: End -->

            </div>
            <!-- Header Grid Container: End -->


            <!-- 100% Box Grid Container: Start -->
            <div class="grid_24">

                <!--<div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                </div>-->

                <!-- Success Notice: Start -->
                <?php if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS)) : ?>
                <div class="notice success">
                    <p><?php echo substr($msgs, 24, -10); ?></p>
                </div>
                <?php endif; ?>
                <!-- Success Notice: End -->

                <!-- Warning Notice: Start -->
                <?php if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_INFO)) : ?>
                <div class="notice warning">
                    <p><?php echo substr($msgs, 24, -10); ?></p>
                </div>
                <?php endif; ?>
                <!-- Warning Notice: End -->

                <!-- Info Notice: Start -->
                <?php if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT)) : ?>
                <div class="notice info">
                    <p><?php echo substr($msgs, 24, -10); ?></p>
                </div>
                <?php endif; ?>
                <!-- Info Notice: End -->

                <!-- Error Notice: Start -->
                <?php if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR)) : ?>
                <div class="notice error">
                    <p><?php echo substr($msgs, 24, -10); ?></p>
                </div>
                <?php endif; ?>
                <!-- Error Notice: End -->
            </div>
            <div>
                <?php echo $this->content; ?>
            </div>
            <!-- 100% Box Grid Container: End -->


            <!-- 100% Box Grid Container: Start -->
<!--            <div class="grid_24">

                 Box Header: Start
                <div class="box_top">

                    <h2 class="icon graph">Visitor Statistics</h2>

                     Graphs Stats Sorting: Start
                    <ul class="sorting">
                        <li><a href="#line" class="active">Line</a></li>
                        <li><a href="#area">Area</a></li>
                        <li><a href="#pie">Pie</a></li>
                        <li><a href="#bar">Bars</a></li>
                    </ul>
                     Graphs Stats Sorting: End

                </div>
                 Box Header: End

                 Box Content: Start
                <div class="box_content">

                     Graphs Stats Table: Start
                    <table class="stats">
                        <thead>
                            <tr>
                                <td></td>
                                <th scope="col"> Jan </th>
                                <th scope="col"> Feb </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row"> Visitors </th>
                                <td> 45 </td>
                                <td> 65 </td>
                            </tr>
                            <tr>
                                <th scope="row"> Returning </th>
                                <td> 34 </td>
                                <td> 34 </td>
                            </tr>
                            <tr>
                                <th scope="row"> Unique </th>
                                <td> 34 </td>
                                <td> 54 </td>
                            </tr>
                        </tbody>
                    </table>
                     Graphs Stats Table: End

                </div>
                 Box Content: End

            </div>-->
            <!-- 100% Box Grid Container: End -->


            <!-- 100% Box Grid Container: Start -->
<!--            <div class="grid_24">

                 Box Header: Start
                <div class="box_top">

                    <a name="gallery"></a>
                    <h2 class="icon pictures">Gallery  <span>45</span></h2>

                     Big Gallery Sorting: Start
                    <ul class="sorting">
                        <li><a href="#" data-type="all" class="active">Show All</a></li>
                        <li><a href="#" data-type="buildings">Buildings</a></li>
                        <li><a href="#" data-type="streets">Streets</a></li>
                        <li><a href="#" data-type="nature">Nature</a></li>
                        <li><a href="#" data-type="clothing">Clothing</a></li>
                    </ul>
                     Big Gallery Sorting: End

                </div>
                 Box Header: End

                 Box Content: Start
                <div class="box_content">

                     Small Gallery Content: Start
                    <ul class="gallery small">

                         Small Gallery Image: Start
                        <li data-type="buildings" data-id="g001">
                            <div class="actions">
                                <a href="#" class="delete">delete</a>
                                <a href="#" class="edit">edit</a>
                                <a href="img/gallery/image_01.jpg" class="view popup">view</a>
                            </div>

                            <a href="img/gallery/image_01.jpg" class="popup">
                                <img src="img/gallery/thumbs_small/image_01.png" alt="" />
                            </a>
                        </li>
                         Small Gallery Image: End

                    </ul>
                     Small Gallery Content: End

                     Small Gallery Footer: Start
                    <div class="padding">
                        <button>Add Image to Gallery</button>

                         Pagination: Start
                        <ul class="pagination right nomargin">
                            <li><a href="#" class="active">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">Next</a></li>
                        </ul>
                         Pagination: End
                    </div>
                     Small Gallery Footer: End

                     Delete Dialog: Start
                    <div id="dialog-confirm" title="Delete this image?">
                        <p>Do you really want to delete this?</p>
                    </div>
                     Delete Dialog: End

                </div>
                 Box Content: End

            </div>-->
            <!-- 100% Box Grid Container: End -->


            <!-- 100% Box Grid Container: Start -->
<!--            <div class="grid_24">

                 Box Header: Start
                <div class="box_top">

                    <a name="news"></a>
                    <h2 class="icon pages">News<span class="tip" title="Tips can be added everywhere">232</span></h2>

                     Tab Select: Start
                    <ul class="sorting">
                        <li><a href="#listing" class="active">Listing</a></li>
                        <li><a href="#addnews">Add News</a></li>
                    </ul>
                     Tab Select: End

                </div>
                 Box Header: End

                 Box Content: Start
                <div class="box_content">

                     News Table Tabs: Start
                    <div class="tabs">

                         News Sorting Table: Start
                        <div id="listing">

                            <table class="sorting">
                                <thead>
                                    <tr>
                                        <th class="checkers"><input type="checkbox" class="checkall" /></th>
                                        <th class="align_left">Title</th>
                                        <th class="align_left center">Author</th>
                                        <th class="align_left center">Views</th>
                                        <th class="align_left center">Comments</th>
                                        <th class="align_left center">Added</th>
                                        <th class="align_left center tools">Tools</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <th class="checkers"><input type="checkbox" /></th>
                                        <td class="align_left"><a href="#">Some technical issues</a></td>
                                        <td class="align_left center"><a href="#messages" class="popup">Kasper</a></td>
                                        <td class="align_left center">12</td>
                                        <td class="align_left center">3</td>
                                        <td class="align_left center">1 hour ago</td>
                                        <td class="align_left tools center">
                                            <a href="#" class="edit tip" title="edit">edit</a>
                                            <a href="#" class="view tip" title="view">view</a>
                                            <a href="#" class="delete tip" title="delete">delete</a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>

                             News Sorting Table Actions: Start
                            <div class="table_actions">
                                <input type="checkbox" class="checkall" />

                                <select>
                                    <option>Choose action</option>
                                    <option>Delete</option>
                                    <option>Edit</option>
                                </select>

                                <button class="left">Apply to Selected</button>
                            </div>
                             News Sorting Table Actions: End

                        </div>
                         News Sorting Table: End

                         News Sorting Table - Add News Tab: Start
                        <div id="addnews" class="padding">

                            <p class="note">
                                <span class="icon info"></span>
                                You could setup your news adding page like this so users can easily add news without going to a new page
                            </p>

                            <div class="field">
                                <label class="left">News Title</label>
                                <input type="text" class="left validate">
                                <p class="error left small nomargin">
                                    <span class="icon cross"></span>
                                    Let the users know what the problem is
                                </p>
                            </div>

                            <div class="field">
                                <label class="left">Tags</label>
                                <input type="text" class="left validate tip-stay" title="Add a tip for focus!">
                                <p class="info left small nomargin">
                                    <span class="icon info"></span>
                                    Or some information about what they should write
                                </p>
                            </div>

                            <div class="field">
                                <label>News Content</label>
                                <textarea class="wysiwyg"></textarea>
                            </div>

                            <button>Publish News</button>
                            <button class="secondary" type="reset">Reset</button>
                            <button disabled="">Disabled Button</button>

                        </div>
                         News Sorting Table - Add News Tab: End

                    </div>
                     News Table Tabs: End

                </div>
                 Box Content: End

            </div>-->
            <!-- 100% Box Grid Container: End -->


            <!-- 75% Box Grid Container: Start -->
<!--            <div class="grid_16">

                 Box Header: Start
                <div class="box_top">

                    <h2 class="icon graph">Latest Activity</h2>

                </div>
                 Box Header: End

                 Box Content: Start
                <div class="box_content">

                     Stats Table: Start
                    <table>

                        <tr>
                            <td>
                                <span class="icon pictures"></span>
                                <a href="#">Kasper</a> added the image <a href="#">My Kitten</a> to the <a href="#">Cats</a> gallery
                            </td>
                            <td class="right_end small">22 hours ago</td>
                        </tr>

                        <tr>
                            <td>
                                <span class="icon pages"></span>
                                <a href="#">Kasper</a> added the news <a href="#">Wow, this feels amazing!</a>
                            </td>
                            <td class="right_end small">22 hours ago</td>
                        </tr>

                    </table>
                     Stats Table: End

                     Pagination: Start
                    <ul class="pagination right">
                        <li><a href="#" class="active">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">Next</a></li>
                    </ul>
                     Pagination: End
                </div>
                 Box Content: End
            </div>
             75% Box Grid Container: End

             25% Box Grid Container: Start
            <div class="grid_8">
                 Box Header: Start
                <div class="box_top">
                    <h2 class="icon graph">Statistics</h2>
                </div>
                 Box Header: End

                 Box Content: Start
                <div class="box_content">

                     Stats Table: Start
                    <table>

                        <tr>
                            <td><span class="icon graph"></span> Status</td>
                            <td class="right_end green">online</td>
                        </tr>

                        <tr>
                            <td><span class="icon pages"></span> Pages</td>
                            <td class="right_end">934</td>
                        </tr>

                    </table>
                     Stats Table: End

                </div>
                 Box Content: End

            </div>-->
            <!-- 25% Box Grid Container: End -->

            <!-- Footer Grid: Start -->
            <div class="grid_24">

                <!-- Footer: Start -->
                <div id="footer">

                    <p class="left">
                        Copyright &#169; 2014 <a href="https://www.cbm.df.gov.br/">CBMDF</a>.
                        Desenvolvido por <a href="mailto:gabrielzerah@gmail.com?Subject=Siscala" target="_top">Gabriel Lima</a>.
                    </p>

                    <!-- Footer Icon Navigation: Start -->
                    <ul class="right">
<!--                        <li><a href="#" class="icon dashboard tip active" title="Dashboard">Dashboard</a></li>
                        <li><a href="#" class="icon pages tip" title="Pages">Pages</a></li>
                        <li><a href="#" class="icon users tip" title="Users">Users</a></li>
                        <li><a href="#" class="icon settings tip" title="Settings">Settings</a></li>
                        <li><a href="#" class="icon support tip" title="Support">Support</a></li>-->
                        <li><a href="<?=$this->url('home', array('controller' => 'index', 'action' => 'index'));?>" class="icon home tip" title="Home">Home</a></li>
                    </ul>
                    <!--Footer Icon Navigation: End -->

                </div>
                <!-- Footer: End -->

            </div>
            <!-- Footer Grid: End -->

        </div>

        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.visualize-tooltip.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery-animate-css-rotate-scale.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery-ui-1.8.13.custom.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.poshytip.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.quicksand.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.dataTables.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.facebox.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.uniform.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.wysiwyg.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.maskedinput.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/jquery.price_format.min.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/syntaxHighlighter/shCore.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/syntaxHighlighter/shBrushXml.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/syntaxHighlighter/shBrushJScript.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/syntaxHighlighter/shBrushCss.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/syntaxHighlighter/shBrushPhp.js"></script>
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/fileTree/jqueryFileTree.js"></script> <!-- Added in 1.2 -->
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/application/js/init.js"></script>

        <!-- jQuery Customization -->
        <script type="text/javascript" src="<?= $this->basePath() ?>/assets/vendor/js/custom.js"></script>
    </body>
</html>
