<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Siscala')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <!-- Template -->
        <link rel="stylesheet/less" type="text/css" href="<?= $this->basePath() ?>/assets/vendorOld/themes/less/bootstrap.less">
        <script src="<?= $this->basePath() ?>/assets/vendorOld/themes/js/less/less.js" type="text/javascript"></script>
        <!-- CSS -->
        <link rel="stylesheet" href="<?= $this->basePath() ?>/assets/vendor/css/stylelogin.css"/>
        <link rel="stylesheet" href="<?= $this->basePath() ?>/assets/vendorOld/themes/style/delta.main.css" />
        <link rel="stylesheet" href="<?= $this->basePath() ?>/assets/vendorOld/themes/style/delta.grey.css"/>
        <!-- SCRIPTS -->
        <script src="<?= $this->basePath() ?>/assets/vendorOld/themes/js/jquery.min.js"></script>
        <script src="<?= $this->basePath() ?>/assets/vendorOld/themes/js/jquery.ui.custom.js"></script>
        <script src="<?= $this->basePath() ?>/assets/vendorOld/themes/js/bootstrap.min.js"></script>
    </head>

    <body>
        <div id="mainBodyLogin">
            <div class="container-fluid">
                <div class="row-fluid">
                    <div class="span12 login-header text-center">
                        <h2>Aréa Adminitrativa</h2>
                    </div><!--/span-->
                </div><!--/row-->
                <div class="row-fluid">
                    <div class="span12 login-box text-center">
                        <?php if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_SUCCESS)) : ?>
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <?php echo $msgs; ?>
                        </div>
                        <?php endif;
                         if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_DEFAULT)) : ?>
                        <div class="alert alert-info">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <?php echo $msgs; ?>
                        </div>
                        <?php endif;
                         if ($msgs = $this->flashMessenger()->render(\Zend\Mvc\Controller\Plugin\FlashMessenger::NAMESPACE_ERROR)) : ?>
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <?php echo $msgs; ?>
                        </div>
                        <?php endif; ?>
                        <?php echo $this->content; ?>
                    </div><!--/span-->
                </div><!--/row-->
            </div>
        </div>

        <?php echo $this->headScript(); ?>

    </body>
</html>
