
<div class="row">
      <div class="col-lg-12">
          <section class="panel">
              <header class="panel-heading">
                  Dados pessoais
              </header>
              <div class="panel-body">
                    <?php
                    $form = $this->form;
                    $form->setAttributes(array('action' => $this->url('autenticacao/default', array('controller' => 'index', 'action' => 'atualizar')), 'name' => 'atualizar', 'class' => ''));
                    $form->prepare();
                    echo $this->form()->openTag($form);
                    echo $this->formHidden($form->get('idUsuario'));
                    ?>
                    <? if ($this->usuarioIdentity()[0]['perfil'] == 'Administrador') :?>
                    <div class="form-group">
                        <label>Perfil:</label>
                        <?php echo $this->formRow($form->get('idRole'));?>
                    </div>
                    <? else: ?>
                        <?php echo $this->formHidden($form->get('idRole'));?>
                    <? endif;?>

                    <div class="form-group">
                        <label>Nome:</label>
                        <?php echo $this->formRow($form->get('nome'));?>
                    </div>

                    <div class="form-group">
                        <label>Email:</label>
                        <?php echo $this->formRow($form->get('email'));?>
                    </div>

                    <div class="form-group">
                        <label>Nova Senha:</label>
                        <?php echo $this->formRow($form->get('password'));?>
                    </div>
                    <?php echo $this->formRow($form->get('Cadastrar')->setValue('Salvar')->setAttributes(array('class'=>'btn btn-info'))); ?>
                    <?php echo $this->form()->closeTag(); ?>
              </div>
          </section>
      </div>
  </div>
