<?php
$form = $this->form;
$form->setAttribute('action', $this->url('autenticacao',array('controller'=>'index','action'=>'index')));
$form->prepare();
echo $this->form()->openTag($form);
?>
<label for="username" class="label_username">Matrícula</label>
<?php echo $this->formRow($form->get('milmatricula'));?>
<!-- Username Input: End -->

<!-- Password Input: Start -->
<label for="password" class="label_password">Senha</label>
<?php echo $this->formRow($form->get('milpassword'));?>
<!-- Password Input: End -->

<!-- Login Button: Start -->
<?php echo $this->formRow($form->get('Entrar'));?>
<?php echo $this->form()->closeTag(); ?>