<div class="box_top">

    <h2 class="icon pages">Paginas restritas</h2>
    <ul class="sorting">
        <li><a href="<?php echo $this->url('acl/default', array('controller' => 'resources', 'action' => 'new')); ?>" class="active">Adicionar página</a></li>
    </ul>

</div>

<div class="box_content">

    <table class="sorting">
        <thead>
            <tr>
                <th class="align_left">ID</th>
                <th class="align_left center">Nome</th>
                <th class="align_left center tools">Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->data as $entity): ?>
                <tr>
                    <td class="align_left"><?php echo $entity->getId(); ?></td>
                    <td class="align_left center"><?php echo $entity->getNome(); ?></td>
                    <td class="align_left tools center">
                        <a href="<?php echo $this->url('acl/default',
                                array('controller'=>'resources','action'=>'edit','id' => $entity->getId())); ?>" class="edit tip" title="edit">edit</a>
                        <a href="<?php echo $this->url('acl/default',
                                array('controller'=>'resources','action'=>'delete','id' => $entity->getId())); ?>" class="delete tip" title="delete">delete</a>
                        <!--<a href="#" class="view tip" title="view">view</a>-->
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php #echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>
