<div class="grid_24">
    <div class="notice info">
        <p>Bem-vindo ao SISCALA! Como a nossa primeira escala ainda não foi montada, <a href="">clique aqui</a> para criar.</p>
    </div>

    <div class="box_top">
        <h2 class="icon time">Links rápidos.</h2>
    </div>
    <div class="box_content">
        <p class="center">
            <a href="<?=$this->url('adm/default', array('controller' => 'militar', 'action' => 'index'));?>" class="big_button add_user"><span>Add Militar</span></a>
            <a href="<?=$this->url('adm/default', array('controller' => 'servico', 'action' => 'index'));?>" class="big_button add_event"><span>Troca de Serviço</span></a>
        </p>
    </div>
</div>

<div class="grid_12">

    <div class="box_top">
            <h2 class="icon pages">Escala 12H</h2>
    </div>
    <div class="box_content">
        <?php if ($this->servico) : ?>
            <?php foreach ($this->servico as $row) : ?>
                <div class="accordion">
                    <h5><a href="#"></a></h5>
                    <div>
                        <p>
                            Cras dictum. Pellentesque habitant morbi tristique senectus et netus
                            et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
                            faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
                            mauris vel est.
                        </p>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>

<div class="grid_12">
    <div class="box_top">
        <h2 class="icon pages">Accordion</h2>
    </div>
    <div class="box_content">
        <div class="accordion">
            <h5><a href="#">Section 1</a></h5>
            <div>
                <p>
                    Cras dictum. Pellentesque habitant morbi tristique senectus et netus
                    et malesuada fames ac turpis egestas. Vestibulum ante ipsum primis in
                    faucibus orci luctus et ultrices posuere cubilia Curae; Aenean lacinia
                    mauris vel est.
                </p>
                <p>
                    Suspendisse eu nisl. Nullam ut libero. Integer dignissim consequat lectus.
                    Class aptent taciti sociosqu ad litora torquent per conubia nostra, per
                    inceptos himenaeos.
                </p>
            </div>
        </div>
    </div>
</div>